<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

$dictionary['NNB_NNB'] = array(
    'table' => 'nnb_nnb',
    'audited' => true,
    'inline_edit' => true,
    'fields' => array (
  'document_name' => 
  array (
    'name' => 'document_name',
    'vname' => 'LBL_NAME',
    'type' => 'name',
    'link' => true,
    'dbType' => 'varchar',
    'len' => '255',
    'required' => true,
    'unified_search' => false,
    'full_text_search' => 
    array (
      'boost' => 3,
    ),
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'merge_filter' => 'disabled',
    'size' => '20',
  ),
  'client_name' => 
  array (
    'required' => false,
    'name' => 'client_name',
    'vname' => 'LBL_CLIENT_NAME',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'nnb_referral_trigger' => 
  array (
    'required' => false,
    'name' => 'nnb_referral_trigger',
    'vname' => 'LBL_NNB_REFERRAL_TRIGGER',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'funding_agency' => 
  array (
    'required' => false,
    'name' => 'funding_agency',
    'vname' => 'LBL_FUNDING_AGENCY',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Funding Agency /Principal (if different  from the Client)',
    'help' => 'Funding Agency /Principal (if different  from the Client)',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'opportunity_spend' => 
  array (
    'required' => false,
    'name' => 'opportunity_spend',
    'vname' => 'LBL_OPPORTUNITY_SPEND ',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Expected Opportunity Spend (Budget) ',
    'help' => 'Expected Opportunity Spend (Budget) ',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '0',
  ),
  'partners' => 
  array (
    'required' => false,
    'name' => 'partners',
    'vname' => 'LBL_PARTNERS',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Consultant partners and the proposed  relationship ',
    'help' => 'Consultant partners and the proposed  relationship ',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'project_value' => 
  array (
    'required' => false,
    'name' => 'project_value',
    'vname' => 'LBL_PROJECT_VALUE',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Expected Project Value ',
    'help' => 'Expected Project Value ',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'procurement_type' => 
  array (
    'required' => false,
    'name' => 'procurement_type',
    'vname' => 'LBL_PROCUREMENT_TYPE',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Proposed procurement type',
    'help' => 'Proposed procurement type',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'jv_revenue' => 
  array (
    'required' => false,
    'name' => 'jv_revenue',
    'vname' => 'LBL_JV_REVENUE',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Expected total JV Revenue (if applicable) ',
    'help' => 'Expected total JV Revenue (if applicable) ',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '0',
  ),
  'contract_duration' => 
  array (
    'required' => false,
    'name' => 'contract_duration',
    'vname' => 'LBL_CONTRACT_DURATION',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Expected contract duration',
    'help' => 'Expected contract duration',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'tender_costs' => 
  array (
    'required' => false,
    'name' => 'tender_costs',
    'vname' => 'LBL_TENDER_COSTS',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Expected tender phase costs',
    'help' => 'Expected tender phase costs',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'payment_terms' => 
  array (
    'required' => false,
    'name' => 'payment_terms',
    'vname' => 'LBL_PAYMENT_TERMS',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'RFP payment terms',
    'help' => 'RFP payment terms',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'scope_of_services' => 
  array (
    'required' => false,
    'name' => 'scope_of_services',
    'vname' => 'LBL_SCOPE_OF_SERVICES',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Brief Scope of Services',
    'help' => 'Brief Scope of Services',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'risks' => 
  array (
    'required' => false,
    'name' => 'risks',
    'vname' => 'LBL_RISKS',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Significant risks & opportunities ',
    'help' => 'Significant risks &amp; opportunities ',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'cashflow_forecast' => 
  array (
    'required' => false,
    'name' => 'cashflow_forecast',
    'vname' => 'LBL_CASHFLOW_FORECAST',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'For NNB due to cash-flow negative  criteria, provide cash-flow forecast. ',
    'help' => 'For NNB due to cash-flow negative  criteria, provide cash-flow forecast. ',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'risk_management' => 
  array (
    'required' => false,
    'name' => 'risk_management',
    'vname' => 'LBL_RISK_MANAGEMENT',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'other_info' => 
  array (
    'required' => false,
    'name' => 'other_info',
    'vname' => 'LBL_OTHER_INFO',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Other relevant information ',
    'help' => 'Other relevant information ',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'proposal_manager' => 
  array (
    'required' => false,
    'name' => 'proposal_manager',
    'vname' => 'LBL_PROPOSAL_MANAGER',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'pi_insurance' => 
  array (
    'required' => false,
    'name' => 'pi_insurance',
    'vname' => 'LBL_PI_INSURANCE',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Proposed arrangement for PI insurance',
    'help' => 'Proposed arrangement for PI insurance',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'smec_revenue' => 
  array (
    'required' => false,
    'name' => 'smec_revenue',
    'vname' => 'LBL_SMEC_REVENUE',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '0',
  ),
  'proposed_payment_terms' => 
  array (
    'required' => false,
    'name' => 'proposed_payment_terms',
    'vname' => 'LBL_PROPOSED_PAYMENT_TERMS',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
),
    'relationships' => array (
),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('NNB_NNB', 'NNB_NNB', array('basic','assignable','security_groups','file'));