<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

$dictionary['Cl_Rating'] = array(
    'table' => 'cl_rating',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array (
  'rating_lab_rev_norm' => 
  array (
    'required' => false,
    'name' => 'rating_lab_rev_norm',
    'vname' => 'LBL_RATING_LAB_REV_NORM',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Total Lab Rev (for Normalization)',
    'help' => 'Total Lab Rev (for Normalization)',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '0',
  ),
  'rating_gp_fact' => 
  array (
    'required' => true,
    'name' => 'rating_gp_fact',
    'vname' => 'LBL_RATING_GP_FACT',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Gross Profit factor approx 10',
    'help' => 'Gross Profit factor approx 10',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '1',
    'default' => '10.0',
  ),
  'rating_ar_days_fact' => 
  array (
    'required' => true,
    'name' => 'rating_ar_days_fact',
    'vname' => 'LBL_RATING_AR_DAYS_FACT',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'AR days factor',
    'help' => 'AR days factor',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'rating_strat_val_fact' => 
  array (
    'required' => true,
    'name' => 'rating_strat_val_fact',
    'vname' => 'LBL_RATING_STRAT_VAL_FACT',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Strat value of client (factor)',
    'help' => 'Strat value of client (factor)',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '1',
    'default' => '5.0',
  ),
  'rating_lab_rev_fact' => 
  array (
    'required' => true,
    'name' => 'rating_lab_rev_fact',
    'vname' => 'LBL_RATING_LAB_REV_FACT',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Lab rev LTD (Normalized by Total Lab Rev)',
    'help' => 'Lab rev LTD (Normalized by Total Lab Rev)',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '1',
    'default' => '2.0',
  ),
  'rating_ar_days_norm' => 
  array (
    'required' => true,
    'name' => 'rating_ar_days_norm',
    'vname' => 'LBL_RATING_AR_DAYS_NORM',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'AR Day (For Normalization) should be 60 days or less',
    'help' => 'AR Day (For Normalization) should be 60 days or less',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '1',
    'default' => '60.0',
  ),
  'rating_strat_val_fact2' => 
  array (
    'required' => true,
    'name' => 'rating_strat_val_fact2',
    'vname' => 'LBL_RATING_STRAT_VAL_FACT2',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Strategic Value/Potential of client (1 to 10)',
    'help' => 'Strategic Value/Potential of client ',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '1',
  ),
  'rating_gp_norm' => 
  array (
    'required' => true,
    'name' => 'rating_gp_norm',
    'vname' => 'LBL_RATING_GP_NORM',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Gross Profit Exp factor approx 0.45',
    'help' => 'Gross Profit Exp factor approx 0.45',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '1',
    'default' => '.5',
  ),
  'rating_overall_weight_fact' => 
  array (
    'required' => true,
    'name' => 'rating_overall_weight_fact',
    'vname' => 'LBL_RATING_OVERALL_WEIGHT_FACT',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Overall Weight factor',
    'help' => 'Overall Weight factor',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '1',
    'default' => '3.0',
  ),
  'sj_division' => 
  array (
    'required' => true,
    'name' => 'sj_division',
    'vname' => 'LBL_SJ_DIVISION',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'SJ_Divisions',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'rating_lab_forecast_fact' => 
  array (
    'required' => true,
    'name' => 'rating_lab_forecast_fact',
    'vname' => 'LBL_RATING_LAB_FORECAST_FACT',
    'type' => 'decimal',
    'massupdate' => 0,
    'default' => '3.0',
    'no_default' => false,
    'comments' => 'Forecast (rolling 12 mnth Normalized by Total Rev)',
    'help' => 'Forecast (rolling 12 mnth Normalized by Total Rev)',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '1',
  ),
  'rating_a_client_bot' => 
  array (
    'required' => true,
    'name' => 'rating_a_client_bot',
    'vname' => 'LBL_RATING_A_CLIENT_BOT',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'Lowest value in client rating envelope',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'rating_b_client_bot' => 
  array (
    'required' => true,
    'name' => 'rating_b_client_bot',
    'vname' => 'LBL_RATING_B_CLIENT_BOT',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Lowest value in client rating envelope',
    'help' => 'Lowest value in client rating envelope',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'rating_c_client_bot' => 
  array (
    'required' => true,
    'name' => 'rating_c_client_bot',
    'vname' => 'LBL_RATING_C_CLIENT_BOT',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Lowest value in client rating envelope',
    'help' => 'Lowest value in client rating envelope',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'rating_d_client_bot' => 
  array (
    'required' => true,
    'name' => 'rating_d_client_bot',
    'vname' => 'LBL_RATING_D_CLIENT_BOT',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Lowest value in client rating envelope',
    'help' => 'Lowest value in client rating envelope',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'acc_ardays_min' => 
  array (
    'required' => false,
    'name' => 'acc_ardays_min',
    'vname' => 'LBL_ACC_ARDAYS_MIN',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '5',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '3',
  ),
  'rating_fcast_norm' => 
  array (
    'required' => false,
    'name' => 'rating_fcast_norm',
    'vname' => 'LBL_RATING_FCAST_NORM',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '0',
  ),
  'rating_np_min' => 
  array (
    'required' => false,
    'name' => 'rating_np_min',
    'vname' => 'LBL_RATING_NP_MIN',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'rating_np_max' => 
  array (
    'required' => false,
    'name' => 'rating_np_max',
    'vname' => 'LBL_RATING_NP_MAX',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'rating_np_norm' => 
  array (
    'required' => false,
    'name' => 'rating_np_norm',
    'vname' => 'LBL_RATING_NP_NORM',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '3',
  ),
  'rating_np_fact' => 
  array (
    'required' => false,
    'name' => 'rating_np_fact',
    'vname' => 'LBL_RATING_NP_FACT',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
),
    'relationships' => array (
),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('Cl_Rating', 'Cl_Rating', array('basic','assignable','security_groups'));